parameters:
    lightsaml.store.request_session_prefix: main
    lightsaml.store.request_session_sufix: saml_request_state_
    lightsaml.store.sso_state_session_key: samlsso

services:
    lightsaml.store.request:
        class: LightSaml\Store\Request\RequestStateSessionStore
        factory: ['LightSaml\SymfonyBridgeBundle\Factory\RequestStateSessionStoreFactory', 'create']

    lightsaml.store.id_state:
        class: LightSaml\Store\Id\NullIdStore

    lightsaml.store.sso_state:
        class: LightSaml\Store\Sso\SsoStateSessionStore
        factory: ['LightSaml\SymfonyBridgeBundle\Factory\SsoStateSessionStoreFactory', 'create']
